namespace NetMvc.Cms.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class RefactorModel : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.Contacts");
            AddColumn("dbo.Abouts", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Abouts", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Abouts", "IsActive", c => c.String());
            AddColumn("dbo.Action", "Status", c => c.Boolean());
            AddColumn("dbo.Action", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Function_Action", "Status", c => c.Boolean());
            AddColumn("dbo.Function_Action", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Functions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Functions", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Functions", "IsActive", c => c.String());
            AddColumn("dbo.Functions", "Status", c => c.Boolean());
            AddColumn("dbo.Functions", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Role_Permission", "Status", c => c.Boolean());
            AddColumn("dbo.Role_Permission", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Albums", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Albums", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Albums", "IsActive", c => c.String());
            AddColumn("dbo.CartItems", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.CartItems", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.CartItems", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.CartItems", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.CartItems", "IsActive", c => c.String());
            AddColumn("dbo.CartItems", "Status", c => c.Boolean());
            AddColumn("dbo.CartItems", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Categories", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Categories", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Categories", "IsActive", c => c.String());
            AddColumn("dbo.Contacts", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Contacts", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Contacts", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Contacts", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Contacts", "IsActive", c => c.String());
            AddColumn("dbo.Feedbacks", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Feedbacks", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Feedbacks", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Feedbacks", "IsActive", c => c.String());
            AddColumn("dbo.Feedbacks", "Status", c => c.Boolean());
            AddColumn("dbo.Feedbacks", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Footers", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Footers", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Footers", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Footers", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Footers", "IsActive", c => c.String());
            AddColumn("dbo.GroupSlides", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.GroupSlides", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.GroupSlides", "IsActive", c => c.String());
            AddColumn("dbo.GroupSlides", "Status", c => c.Boolean());
            AddColumn("dbo.GroupSlides", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Languages", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Languages", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Languages", "IsActive", c => c.String());
            AddColumn("dbo.Languages", "Status", c => c.Boolean());
            AddColumn("dbo.Languages", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Menus", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Menus", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Menus", "IsActive", c => c.String());
            AddColumn("dbo.Menus", "Status", c => c.Boolean());
            AddColumn("dbo.Menus", "LanguageCode", c => c.String(maxLength: 10, unicode: false));
            AddColumn("dbo.MenuTypes", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.MenuTypes", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.MenuTypes", "IsActive", c => c.String());
            AddColumn("dbo.MenuTypes", "Status", c => c.Boolean());
            AddColumn("dbo.MenuTypes", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Newses", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Newses", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Newses", "IsActive", c => c.String());
            AddColumn("dbo.NewsTags", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.NewsTags", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.NewsTags", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.NewsTags", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.NewsTags", "IsActive", c => c.String());
            AddColumn("dbo.NewsTags", "Status", c => c.Boolean());
            AddColumn("dbo.NewsTags", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.OrderDetails", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.OrderDetails", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.OrderDetails", "IsActive", c => c.String());
            AddColumn("dbo.OrderDetails", "Status", c => c.Boolean());
            AddColumn("dbo.OrderDetails", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Orders", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Orders", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Orders", "IsActive", c => c.String());
            AddColumn("dbo.Orders", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Permissions", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Permissions", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Permissions", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Permissions", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Permissions", "IsActive", c => c.String());
            AddColumn("dbo.Permissions", "Status", c => c.Boolean());
            AddColumn("dbo.Permissions", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Photos", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Photos", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Photos", "IsActive", c => c.String());
            AddColumn("dbo.Photos", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.ProductCategories", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.ProductCategories", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.ProductCategories", "IsActive", c => c.String());
            AddColumn("dbo.Products", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Products", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Products", "IsActive", c => c.String());
            AddColumn("dbo.Slides", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Slides", "CreatedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Slides", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Slides", "ModifiedBy", c => c.String(maxLength: 50));
            AddColumn("dbo.Slides", "IsActive", c => c.String());
            AddColumn("dbo.Slides", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.SystemConfigs", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.SystemConfigs", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.SystemConfigs", "IsActive", c => c.String());
            AddColumn("dbo.SystemConfigs", "Status", c => c.Boolean());
            AddColumn("dbo.SystemConfigs", "LanguageCode", c => c.String(maxLength: 10));
            AddColumn("dbo.Tags", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.Tags", "ModifiedBy", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.Tags", "IsActive", c => c.String());
            AddColumn("dbo.Tags", "Status", c => c.Boolean());
            AddColumn("dbo.Tags", "LanguageCode", c => c.String(maxLength: 10));
            AlterColumn("dbo.Abouts", "Status", c => c.Boolean());
            AlterColumn("dbo.Abouts", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Abouts", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Functions", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Functions", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Albums", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Categories", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Categories", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Categories", "LanguageCode", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.Contacts", "Status", c => c.Boolean());
            AlterColumn("dbo.Feedbacks", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Footers", "Status", c => c.Boolean());
            AlterColumn("dbo.GroupSlides", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.GroupSlides", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Languages", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Languages", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Menus", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Menus", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.MenuTypes", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.MenuTypes", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Newses", "Status", c => c.Boolean());
            AlterColumn("dbo.Newses", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Newses", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Orders", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ProductCategories", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.ProductCategories", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.ProductCategories", "LanguageCode", c => c.String(maxLength: 10, unicode: false));
            AlterColumn("dbo.Products", "Status", c => c.Boolean());
            AlterColumn("dbo.Products", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Products", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Slides", "Status", c => c.Boolean());
            AlterColumn("dbo.SystemConfigs", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.SystemConfigs", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.Tags", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Tags", "CreatedBy", c => c.String(maxLength: 50, unicode: false));
            AddPrimaryKey("dbo.Contacts", new[] { "ID", "Title" });
            DropColumn("dbo.Abouts", "UpdatedDate");
            DropColumn("dbo.Abouts", "UpdatedBy");
            DropColumn("dbo.Functions", "UpdatedDate");
            DropColumn("dbo.Functions", "UpdatedBy");
            DropColumn("dbo.GroupSlides", "UpdatedDate");
            DropColumn("dbo.GroupSlides", "UpdatedBy");
            DropColumn("dbo.Languages", "UpdatedDate");
            DropColumn("dbo.Languages", "UpdatedBy");
            DropColumn("dbo.Menus", "UpdatedDate");
            DropColumn("dbo.Menus", "UpdatedBy");
            DropColumn("dbo.Menus", "Language");
            DropColumn("dbo.Newses", "UpdatedDate");
            DropColumn("dbo.Newses", "UpdatedBy");
            DropColumn("dbo.ProductCategories", "UpdatedDate");
            DropColumn("dbo.ProductCategories", "UpdatedBy");
            DropColumn("dbo.Products", "UpdatedDate");
            DropColumn("dbo.Products", "UpdatedBy");
            DropColumn("dbo.SystemConfigs", "UpdatedDate");
            DropColumn("dbo.SystemConfigs", "UpdatedBy");
            DropColumn("dbo.Tags", "UpdatedDate");
            DropColumn("dbo.Tags", "UpdatedBy");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Tags", "UpdatedBy", c => c.String(maxLength: 20, unicode: false));
            AddColumn("dbo.Tags", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.SystemConfigs", "UpdatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AddColumn("dbo.SystemConfigs", "UpdatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Products", "UpdatedBy", c => c.String(maxLength: 10, unicode: false));
            AddColumn("dbo.Products", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.ProductCategories", "UpdatedBy", c => c.String(maxLength: 20, unicode: false));
            AddColumn("dbo.ProductCategories", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Newses", "UpdatedBy", c => c.String(maxLength: 10, unicode: false));
            AddColumn("dbo.Newses", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Menus", "Language", c => c.String(maxLength: 10, unicode: false));
            AddColumn("dbo.Menus", "UpdatedBy", c => c.String(maxLength: 20, unicode: false));
            AddColumn("dbo.Menus", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Languages", "UpdatedBy", c => c.String(maxLength: 20, unicode: false));
            AddColumn("dbo.Languages", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.GroupSlides", "UpdatedBy", c => c.String(maxLength: 20, unicode: false));
            AddColumn("dbo.GroupSlides", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Functions", "UpdatedBy", c => c.String(maxLength: 20, unicode: false));
            AddColumn("dbo.Functions", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Abouts", "UpdatedBy", c => c.String(maxLength: 10, unicode: false));
            AddColumn("dbo.Abouts", "UpdatedDate", c => c.DateTime());
            DropPrimaryKey("dbo.Contacts");
            AlterColumn("dbo.Tags", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Tags", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.SystemConfigs", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.SystemConfigs", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Slides", "Status", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Products", "CreatedBy", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.Products", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Products", "Status", c => c.Int(nullable: false));
            AlterColumn("dbo.ProductCategories", "LanguageCode", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.ProductCategories", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.ProductCategories", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Orders", "CreatedBy", c => c.String());
            AlterColumn("dbo.Newses", "CreatedBy", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.Newses", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Newses", "Status", c => c.Int(nullable: false));
            AlterColumn("dbo.MenuTypes", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.MenuTypes", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Menus", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Menus", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Languages", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Languages", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GroupSlides", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.GroupSlides", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Footers", "Status", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Feedbacks", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Contacts", "Status", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Categories", "LanguageCode", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.Categories", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Categories", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Albums", "CreatedBy", c => c.String(maxLength: 20, unicode: false));
            AlterColumn("dbo.Functions", "CreatedBy", c => c.String(nullable: false, maxLength: 20, unicode: false));
            AlterColumn("dbo.Functions", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Abouts", "CreatedBy", c => c.String(nullable: false, maxLength: 10, unicode: false));
            AlterColumn("dbo.Abouts", "CreatedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Abouts", "Status", c => c.Int(nullable: false));
            DropColumn("dbo.Tags", "LanguageCode");
            DropColumn("dbo.Tags", "Status");
            DropColumn("dbo.Tags", "IsActive");
            DropColumn("dbo.Tags", "ModifiedBy");
            DropColumn("dbo.Tags", "ModifiedDate");
            DropColumn("dbo.SystemConfigs", "LanguageCode");
            DropColumn("dbo.SystemConfigs", "Status");
            DropColumn("dbo.SystemConfigs", "IsActive");
            DropColumn("dbo.SystemConfigs", "ModifiedBy");
            DropColumn("dbo.SystemConfigs", "ModifiedDate");
            DropColumn("dbo.Slides", "LanguageCode");
            DropColumn("dbo.Slides", "IsActive");
            DropColumn("dbo.Slides", "ModifiedBy");
            DropColumn("dbo.Slides", "ModifiedDate");
            DropColumn("dbo.Slides", "CreatedBy");
            DropColumn("dbo.Slides", "CreatedDate");
            DropColumn("dbo.Products", "IsActive");
            DropColumn("dbo.Products", "ModifiedBy");
            DropColumn("dbo.Products", "ModifiedDate");
            DropColumn("dbo.ProductCategories", "IsActive");
            DropColumn("dbo.ProductCategories", "ModifiedBy");
            DropColumn("dbo.ProductCategories", "ModifiedDate");
            DropColumn("dbo.Photos", "LanguageCode");
            DropColumn("dbo.Photos", "IsActive");
            DropColumn("dbo.Photos", "ModifiedBy");
            DropColumn("dbo.Photos", "ModifiedDate");
            DropColumn("dbo.Permissions", "LanguageCode");
            DropColumn("dbo.Permissions", "Status");
            DropColumn("dbo.Permissions", "IsActive");
            DropColumn("dbo.Permissions", "ModifiedBy");
            DropColumn("dbo.Permissions", "ModifiedDate");
            DropColumn("dbo.Permissions", "CreatedBy");
            DropColumn("dbo.Permissions", "CreatedDate");
            DropColumn("dbo.Orders", "LanguageCode");
            DropColumn("dbo.Orders", "IsActive");
            DropColumn("dbo.Orders", "ModifiedBy");
            DropColumn("dbo.Orders", "ModifiedDate");
            DropColumn("dbo.OrderDetails", "LanguageCode");
            DropColumn("dbo.OrderDetails", "Status");
            DropColumn("dbo.OrderDetails", "IsActive");
            DropColumn("dbo.OrderDetails", "ModifiedBy");
            DropColumn("dbo.OrderDetails", "ModifiedDate");
            DropColumn("dbo.OrderDetails", "CreatedBy");
            DropColumn("dbo.OrderDetails", "CreatedDate");
            DropColumn("dbo.NewsTags", "LanguageCode");
            DropColumn("dbo.NewsTags", "Status");
            DropColumn("dbo.NewsTags", "IsActive");
            DropColumn("dbo.NewsTags", "ModifiedBy");
            DropColumn("dbo.NewsTags", "ModifiedDate");
            DropColumn("dbo.NewsTags", "CreatedBy");
            DropColumn("dbo.NewsTags", "CreatedDate");
            DropColumn("dbo.Newses", "IsActive");
            DropColumn("dbo.Newses", "ModifiedBy");
            DropColumn("dbo.Newses", "ModifiedDate");
            DropColumn("dbo.MenuTypes", "LanguageCode");
            DropColumn("dbo.MenuTypes", "Status");
            DropColumn("dbo.MenuTypes", "IsActive");
            DropColumn("dbo.MenuTypes", "ModifiedBy");
            DropColumn("dbo.MenuTypes", "ModifiedDate");
            DropColumn("dbo.Menus", "LanguageCode");
            DropColumn("dbo.Menus", "Status");
            DropColumn("dbo.Menus", "IsActive");
            DropColumn("dbo.Menus", "ModifiedBy");
            DropColumn("dbo.Menus", "ModifiedDate");
            DropColumn("dbo.Languages", "LanguageCode");
            DropColumn("dbo.Languages", "Status");
            DropColumn("dbo.Languages", "IsActive");
            DropColumn("dbo.Languages", "ModifiedBy");
            DropColumn("dbo.Languages", "ModifiedDate");
            DropColumn("dbo.GroupSlides", "LanguageCode");
            DropColumn("dbo.GroupSlides", "Status");
            DropColumn("dbo.GroupSlides", "IsActive");
            DropColumn("dbo.GroupSlides", "ModifiedBy");
            DropColumn("dbo.GroupSlides", "ModifiedDate");
            DropColumn("dbo.Footers", "IsActive");
            DropColumn("dbo.Footers", "ModifiedBy");
            DropColumn("dbo.Footers", "ModifiedDate");
            DropColumn("dbo.Footers", "CreatedBy");
            DropColumn("dbo.Footers", "CreatedDate");
            DropColumn("dbo.Feedbacks", "LanguageCode");
            DropColumn("dbo.Feedbacks", "Status");
            DropColumn("dbo.Feedbacks", "IsActive");
            DropColumn("dbo.Feedbacks", "ModifiedBy");
            DropColumn("dbo.Feedbacks", "ModifiedDate");
            DropColumn("dbo.Feedbacks", "CreatedBy");
            DropColumn("dbo.Contacts", "IsActive");
            DropColumn("dbo.Contacts", "ModifiedBy");
            DropColumn("dbo.Contacts", "ModifiedDate");
            DropColumn("dbo.Contacts", "CreatedBy");
            DropColumn("dbo.Contacts", "CreatedDate");
            DropColumn("dbo.Categories", "IsActive");
            DropColumn("dbo.Categories", "ModifiedBy");
            DropColumn("dbo.Categories", "ModifiedDate");
            DropColumn("dbo.CartItems", "LanguageCode");
            DropColumn("dbo.CartItems", "Status");
            DropColumn("dbo.CartItems", "IsActive");
            DropColumn("dbo.CartItems", "ModifiedBy");
            DropColumn("dbo.CartItems", "ModifiedDate");
            DropColumn("dbo.CartItems", "CreatedBy");
            DropColumn("dbo.CartItems", "CreatedDate");
            DropColumn("dbo.Albums", "IsActive");
            DropColumn("dbo.Albums", "ModifiedBy");
            DropColumn("dbo.Albums", "ModifiedDate");
            DropColumn("dbo.Role_Permission", "LanguageCode");
            DropColumn("dbo.Role_Permission", "Status");
            DropColumn("dbo.Functions", "LanguageCode");
            DropColumn("dbo.Functions", "Status");
            DropColumn("dbo.Functions", "IsActive");
            DropColumn("dbo.Functions", "ModifiedBy");
            DropColumn("dbo.Functions", "ModifiedDate");
            DropColumn("dbo.Function_Action", "LanguageCode");
            DropColumn("dbo.Function_Action", "Status");
            DropColumn("dbo.Action", "LanguageCode");
            DropColumn("dbo.Action", "Status");
            DropColumn("dbo.Abouts", "IsActive");
            DropColumn("dbo.Abouts", "ModifiedBy");
            DropColumn("dbo.Abouts", "ModifiedDate");
            AddPrimaryKey("dbo.Contacts", new[] { "ID", "Title", "Status" });
        }
    }
}
